### PR TITLE
composition functions in Monocle.Compose

### PR DESCRIPTION
**Pull request by Bastes**
Implementing this crazy idea: https://github.com/arturopala/elm-monocle/issues/20

Also upgrading the tests with elm-explorations/test (the new version of elm-community/elm-test)

### CODE REVIEW

**Comment by Bastes** [comment]
Looks like semaphore fails at `yarn install-with-elm` ; I don't know why nor how to fix it yet :/ I'll try whatever I find but don't hesitate to tell me if you have a theory :)

**Comment by Bastes** [comment]
I thought it would work but it seems the tests are hanging on semaphore or something ^^°

**Comment by Bastes** [comment]
So, good news is, the tests start. Bad news is, it hangs to the death apparently. I'm going to try and re-launch it and see if it's consistent.

**Comment by Bastes** [comment]
Yep. Re-launched, and apparently still hanging ^^° I don't know how to debug it. If you have a good idea, I'm listening.

**Comment by Bastes** [comment]
(if it helps, the tests all pass when I run them at home in about 2119ms)
``
`
elm-test 0.19.0-beta9
---------------------

Running 203 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 134664137701840 /Users/michelbelleville/Projects/perso/elm-monocle/tests/CommonSpec.elm /Users/michelbelleville/Projects/perso/elm-monocle/tests/ComposeSpec.elm /Users/michelbelleville/Projects/perso/elm-monocle/tests/IsoSpec.elm /Users/michelbelleville/Projects/perso/elm-monocle/tests/LensSpec.elm /Users/michelbelleville/Projects/perso/elm-monocle/tests/OptionalSpec.elm /Users/michelbelleville/Projects/perso/elm-monocle/tests/PrismSpec.elm /Users/michelbelleville/Projects/perso/elm-monocle/tests/Tests.elm


TEST RUN PASSED

Duration: 2119 ms
Passed:   203
Failed:   0
```

**Comment by arturopala** [comment]
Hello @Bastes, well done! Thank you for your contribution. I have just released the change as version 2.1.0.

**Comment by Bastes** [comment]
Yay \o/ thanks Artur :)

**Pull request merged**
